[env]
framework = arduino
lib_deps =
    GyverLibs/AutoOTA
    GyverLibs/Settings
    GyverLibs/GSON
    GyverLibs/GyverHTTP
    bodmer/TFT_eSPI@2.4.79

[env:cyd]
platform = espressif32
board = esp32dev
upload_speed = 115200
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, default
build_type = debug
board_build.filesystem = littlefs
build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_MISO=12
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D TOUCH_CS=33
